#!/usr/bin/env python3

import argparse
import logging; log = logging.getLogger('ps-client')

import pubsub.args

def main (args) :
    """
        Publish-Subscribe client.
    """

    parser = argparse.ArgumentParser(description=__doc__)

    pubsub.args.parser(parser)
    
    parser.add_argument('-s', '--server-ip', metavar='IP',
            help="Publish server address")
    parser.add_argument('-p', '--server-port', metavar='PORT',
            help="Publish server port")
    parser.add_argument('sensors', metavar='SENSOR', nargs='*',
            help="Sensors to subscribe to")

    args = parser.parse_args(args)
    
    pubsub.args.apply(args)

    log.info("server=%s:%s, sensors=%s", args.server_ip, args.server_port, args.sensors)

    return 0

if __name__ == '__main__':
    pubsub.args.main(main)
