#!/usr/bin/env python3

import argparse
import logging; log = logging.getLogger('ps-server')

import pubsub.args

def main (args) :
    """
        Publish-Subscribe server.
    """

    parser = argparse.ArgumentParser(description=__doc__)

    pubsub.args.parser(parser)

    parser.add_argument('-p', '--publish-port', metavar='PORT',
            help="Receive sensor updates")
    parser.add_argument('-s', '--subscribe-port', metavar='PORT',
            help="Receive client subscribes")

    args = parser.parse_args(args)
    
    pubsub.args.apply(args)

    log.info("publish=%s, subscribe=%s", args.publish_port, args.subscribe_port)

    return 0

if __name__ == '__main__':
    pubsub.args.main(main)
